### ISSUE TITLE
Rjsniffer.amICompromised returns true on Android emulator API 30

### ISSUE THREAD

**Issue by Z6P0** [romikavinda/root_jailbreak_sniffer#1]
I tested with different emulators, all return false, except this one.

Error log:

```
  V/RootBeer( 7983): RootBeer: checkForDangerousProps() [283] - ro.debuggable = [1] detected!
  D/RootInspector( 7983): --> Full response was: []
```

**Comment by romikavinda** [comment]
Hi, seems like this is due to native RootBeer package identifying the device as rooted due to detecting ro.debuggable = [1] , I'll post an update when a fix is issued for the RootBeer package.
