### ISSUE TITLE
ANR when released to play store

### ISSUE THREAD

**Issue by SuganyaRajendran0207** [romikavinda/root_jailbreak_sniffer#2]
I added rooted and emulator validation in app and it is working fine in android debug. After submitting app to play store, it get rejected and i received the ANR log in pre-launch report. 

Flutter version: 3.13.9
dart version: 3.1.5

i added this validation in flutter splash screen.

`
  Future<bool> isRooted() async {
    return await Rjsniffer.amICompromised() ?? false;
  }
` 

`Future<bool> isEmulator() async {
     return await Rjsniffer.amIEmulator() ?? false;
  }
`

**Error log:**

This is the log i received in playstore report
  
> 06-25 23:33:35.896  1468  1568 W ActivityManager: Timeout executing service: ServiceRecord{b3aa469 u0 *****application_id*****/com.emrys.rjsniffer.rjsniffer.Sniffer}
06-25 23:33:35.931  1468 20607 I ActivityManager: dumpStackTraces pids=null nativepids=null
06-25 23:33:35.932  1468 20607 I ActivityManager: Dumping to /data/anr/anr_2024-06-26-02-33-35-932
06-25 23:33:35.932  1468 20607 I ActivityManager: Collecting stacks for pid 19827
06-25 23:33:35.933  1468 20607 I system_server: libdebuggerd_client: started dumping process 19827
06-25 23:33:35.933   570   570 I tombstoned: registered intercept for pid 19827 and type kDebuggerdJavaBacktrace
06-25 23:33:35.934 19827 19832 I sniffer.Sniffe: Thread[6,tid=19832,WaitingInMainSignalCatcherLoop,Thread*=0x745de852c0,peer=0x12e00d10,"Signal Catcher"]: reacting to signal 3
06-25 23:33:35.934 19827 19832 I sniffer.Sniffe: 
06-25 23:33:35.988   570   570 I tombstoned: received crash request for pid 19827
06-25 23:33:35.988   570   570 I tombstoned: found intercept fd 512 for pid 19827 and type kDebuggerdJavaBacktrace
06-25 23:33:35.988 19827 19832 I sniffer.Sniffe: Wrote stack traces to tombstoned
06-25 23:33:35.988   570   570 W tombstoned: missing output fd
06-25 23:33:35.988  1468 20607 I system_server: libdebuggerd_client: done dumping process 19827
06-25 23:33:35.990  1468 20607 I ActivityManager: Done dumping
06-25 23:33:35.992  1468 20607 E ActivityManager: **ANR** in *****application_id*****:com.emrys.rjsniffer.rjsniffer.Sniffer
06-25 23:33:35.992  1468 20607 E ActivityManager: PID: 19827
06-25 23:33:35.992  1468 20607 E ActivityManager: Reason: executing service *****application_id*****/com.emrys.rjsniffer.rjsniffer.Sniffer
06-25 23:33:35.992  1468 20607 E ActivityManager: Frozen: false
06-25 23:33:35.992  1468 20607 E ActivityManager: Load: 0.0 / 0.0 / 0.0
06-25 23:33:35.992  1468 20607 E ActivityManager: ----- Output from /proc/pressure/memory -----
06-25 23:33:35.992  1468 20607 E ActivityManager: some avg10=0.23 avg60=0.60 avg300=0.24 total=1811497
06-25 23:33:35.992  1468 20607 E ActivityManager: full avg10=0.00 avg60=0.01 avg300=0.00 total=466765
06-25 23:33:35.992  1468 20607 E ActivityManager: ----- End output from /proc/pressure/memory -----
06-25 23:33:35.992  1468 20607 E ActivityManager:

**Comment by romikavinda** [comment]
Hi,
Can you check the release version of the app before submitting it to google play? (flutter run --release) , this package is used in apps without any issues which are available on google play. 
Flutter version: 3.16.9
dart version: 3.2.6
